version: "3"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOW_ORIGIN=${ALLOW_ORIGINS}
    volumes:
      - ./data:/data
